on:
  push:
    branches:
      - main
jobs:
  trigger_build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build of web UI
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: hobofan/bcr-web-ui
          token: ${{ secrets.WEB_UI_REPO_ACCESS_TOKEN }}
          event-type: on-bcr-trigger
          client-payload: '{"bcrCommitHash": "${{ github.sha }}"}'
